#!/bin/sh

##    Copyright © 2016 Rowan Thorpe, initially based entirely on a "taskdb" demo-app
##    posted by Joe Bognor at http://picolisp.com/wiki/?taskdb on 24 August 2016, and
##    intended to develop extensively from there.
##
##    This file is part of Picotask.
##
##    Picotask is free software: you can redistribute it and/or modify
##    it under the terms of the GNU Affero General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    Picotask is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU Affero General Public License for more details.
##
##    You should have received a copy of the GNU Affero General Public License
##    along with Picotask.  If not, see <http://www.gnu.org/licenses/>.

cmdline='__PL_PREFIX__/bin/picolisp __PL_PREFIX__/lib/picolisp/lib.l -"load \"__CONFDIR__/picotask.l\" \"__LIBDIR__/libpicotask.l\"" -\"ptask~connectdb\"'

case "$1" in
    -h|--help)
        cat <<EOF
Usage: $(printf '%s' "$0" | sed -e 's:^.*/\([^/]\+\)$:\1:') [ARGS]

Picolisp task-manager. With no args, runs interactively. Enter (ptask~help) in
the prompt for info. Enter (bye) to exit.

ARGS:
 Forces non-interactive use. Enter shell-escaped picolisp commands without
 enclosing parentheses (like what is used for normal noninteractive use of
 picolisp). For example:

  picotask 'ptask~help'

 executes as:

  ${cmdline} -'ptask~help' -bye

EOF
        exit 0
        ;;
esac

if test $# -ne 0; then
    for _arg do
        cmdline="${cmdline} -'$(printf '%s' "${_arg}" | sed -r -e "s/'/'\\\\''/g")'"
    done
    eval "exec $cmdline -bye"
##TODO: not yet working (why?)
#elif ! tty -s; then
#    eval "exec $cmdline -\"in NIL (run (till NIL T))\" -bye"
else
    eval "exec $cmdline +"
fi
